export const interestList = [
	{ label: "Biology", value: "biology" },
	{ label: "Chemistry", value: "chemistry" },
	{ label: "Physics", value: "physics" },
	{ label: "Mathematics", value: "mathematics" },
	{ label: "Computer Science", value: "computer science" },
	{ label: "Psychology", value: "psychology" },
	{ label: "Sociology", value: "sociology" },
	{ label: "History", value: "history" },
	{ label: "Literature", value: "literature" },
	{ label: "Political Science", value: "political science" },
	{ label: "Economics", value: "economics" },
	{ label: "Environmental Science", value: "environmental science" },
	{ label: "Medicine", value: "medicine" },
	{ label: "Engineering", value: "engineering" },
	{ label: "Anthropology", value: "anthropology" },
];

export const preferenceList = [
	{ label: "Data Analysis", value: "data analysis" },
	{ label: "Experimentation", value: "experimentation" },
	{ label: "Literature Review", value: "literature review" },
	{ label: "Statistical Modeling", value: "statistical modeling" },
	{ label: "Coding", value: "coding" },
	{ label: "Survey Design", value: "survey design" },
	{ label: "Interviewing", value: "interviewing" },
	{ label: "Qualitative Analysis", value: "qualitative analysis" },
	{ label: "Quantitative Analysis", value: "quantitative analysis" },
	{ label: "Collaborative Writing", value: "collaborative writing" },
	{ label: "Peer Review", value: "peer review" },
	{ label: "Presentation Skills", value: "presentation skills" },
	{ label: "Citation Management", value: "citation management" },
	{ label: "Research Methodology", value: "research methodology" },
	{ label: "Project Management", value: "project management" },
];
